name: CI

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Secret Dection
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: ${{ github.workspace }}/.github/config/.gitleaks.toml
        continue-on-error: false

      - name: Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          config: ${{ github.workspace }}/.github/config/.hadolint.yml

      - name: Trojan Source Detector
        uses: haveyoudebuggedit/trojansourcedetector@v1
        with:
          config: .github/config/.trojansourcedetector.json
