name: Release

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: main
        required: true

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
        if: github.event.inputs.git-ref == 'main'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
        if: github.event.inputs.git-ref == 'main'

      - name: Install dependencies
        run: npm install
        if: github.event.inputs.git-ref == 'main'

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.inputs.git-ref == 'main'
